/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StyleTestRouteImport } from './routes/style-test'
import { Route as SpotsRouteImport } from './routes/spots'
import { Route as MyCourseRouteImport } from './routes/my-course'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SpotsIdRouteImport } from './routes/spots_.$id'
import { Route as SpotsIdRouteImport } from './routes/spots.$id'
import { Route as SpotsIdNearbyRouteImport } from './routes/spots.$id.nearby'
import { Route as SpotsIdNearbyItemIdRouteImport } from './routes/spots.$id.nearby.$itemId'

const StyleTestRoute = StyleTestRouteImport.update({
  id: '/style-test',
  path: '/style-test',
  getParentRoute: () => rootRouteImport,
} as any)
const SpotsRoute = SpotsRouteImport.update({
  id: '/spots',
  path: '/spots',
  getParentRoute: () => rootRouteImport,
} as any)
const MyCourseRoute = MyCourseRouteImport.update({
  id: '/my-course',
  path: '/my-course',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpotsIdRoute = SpotsIdRouteImport.update({
  id: '/spots_/$id',
  path: '/spots/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SpotsIdRoute = SpotsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SpotsRoute,
} as any)
const SpotsIdNearbyRoute = SpotsIdNearbyRouteImport.update({
  id: '/nearby',
  path: '/nearby',
  getParentRoute: () => SpotsIdRoute,
} as any)
const SpotsIdNearbyItemIdRoute = SpotsIdNearbyItemIdRouteImport.update({
  id: '/$itemId',
  path: '/$itemId',
  getParentRoute: () => SpotsIdNearbyRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/my-course': typeof MyCourseRoute
  '/spots': typeof SpotsRouteWithChildren
  '/style-test': typeof StyleTestRoute
  '/spots/$id': typeof SpotsIdRoute
  '/spots/$id/nearby': typeof SpotsIdNearbyRouteWithChildren
  '/spots/$id/nearby/$itemId': typeof SpotsIdNearbyItemIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/my-course': typeof MyCourseRoute
  '/spots': typeof SpotsRouteWithChildren
  '/style-test': typeof StyleTestRoute
  '/spots/$id': typeof SpotsIdRoute
  '/spots/$id/nearby': typeof SpotsIdNearbyRouteWithChildren
  '/spots/$id/nearby/$itemId': typeof SpotsIdNearbyItemIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/my-course': typeof MyCourseRoute
  '/spots': typeof SpotsRouteWithChildren
  '/style-test': typeof StyleTestRoute
  '/spots/$id': typeof SpotsIdRouteWithChildren
  '/spots_/$id': typeof SpotsIdRoute
  '/spots/$id/nearby': typeof SpotsIdNearbyRouteWithChildren
  '/spots/$id/nearby/$itemId': typeof SpotsIdNearbyItemIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/my-course'
    | '/spots'
    | '/style-test'
    | '/spots/$id'
    | '/spots/$id/nearby'
    | '/spots/$id/nearby/$itemId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/my-course'
    | '/spots'
    | '/style-test'
    | '/spots/$id'
    | '/spots/$id/nearby'
    | '/spots/$id/nearby/$itemId'
  id:
    | '__root__'
    | '/'
    | '/my-course'
    | '/spots'
    | '/style-test'
    | '/spots/$id'
    | '/spots_/$id'
    | '/spots/$id/nearby'
    | '/spots/$id/nearby/$itemId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MyCourseRoute: typeof MyCourseRoute
  SpotsRoute: typeof SpotsRouteWithChildren
  StyleTestRoute: typeof StyleTestRoute
  SpotsIdRoute: typeof SpotsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/style-test': {
      id: '/style-test'
      path: '/style-test'
      fullPath: '/style-test'
      preLoaderRoute: typeof StyleTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spots': {
      id: '/spots'
      path: '/spots'
      fullPath: '/spots'
      preLoaderRoute: typeof SpotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-course': {
      id: '/my-course'
      path: '/my-course'
      fullPath: '/my-course'
      preLoaderRoute: typeof MyCourseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spots_/$id': {
      id: '/spots_/$id'
      path: '/spots/$id'
      fullPath: '/spots/$id'
      preLoaderRoute: typeof SpotsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spots/$id': {
      id: '/spots/$id'
      path: '/$id'
      fullPath: '/spots/$id'
      preLoaderRoute: typeof SpotsIdRouteImport
      parentRoute: typeof SpotsRoute
    }
    '/spots/$id/nearby': {
      id: '/spots/$id/nearby'
      path: '/nearby'
      fullPath: '/spots/$id/nearby'
      preLoaderRoute: typeof SpotsIdNearbyRouteImport
      parentRoute: typeof SpotsIdRoute
    }
    '/spots/$id/nearby/$itemId': {
      id: '/spots/$id/nearby/$itemId'
      path: '/$itemId'
      fullPath: '/spots/$id/nearby/$itemId'
      preLoaderRoute: typeof SpotsIdNearbyItemIdRouteImport
      parentRoute: typeof SpotsIdNearbyRoute
    }
  }
}

interface SpotsIdNearbyRouteChildren {
  SpotsIdNearbyItemIdRoute: typeof SpotsIdNearbyItemIdRoute
}

const SpotsIdNearbyRouteChildren: SpotsIdNearbyRouteChildren = {
  SpotsIdNearbyItemIdRoute: SpotsIdNearbyItemIdRoute,
}

const SpotsIdNearbyRouteWithChildren = SpotsIdNearbyRoute._addFileChildren(
  SpotsIdNearbyRouteChildren,
)

interface SpotsIdRouteChildren {
  SpotsIdNearbyRoute: typeof SpotsIdNearbyRouteWithChildren
}

const SpotsIdRouteChildren: SpotsIdRouteChildren = {
  SpotsIdNearbyRoute: SpotsIdNearbyRouteWithChildren,
}

const SpotsIdRouteWithChildren =
  SpotsIdRoute._addFileChildren(SpotsIdRouteChildren)

interface SpotsRouteChildren {
  SpotsIdRoute: typeof SpotsIdRouteWithChildren
}

const SpotsRouteChildren: SpotsRouteChildren = {
  SpotsIdRoute: SpotsIdRouteWithChildren,
}

const SpotsRouteWithChildren = SpotsRoute._addFileChildren(SpotsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MyCourseRoute: MyCourseRoute,
  SpotsRoute: SpotsRouteWithChildren,
  StyleTestRoute: StyleTestRoute,
  SpotsIdRoute: SpotsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
